#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Apr 12 09:28:06 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class FileView(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FileView.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.fileView_ctrl = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_RICH|wx.TE_WORDWRAP)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FileView.__set_properties
        self.SetTitle("File")
        self.SetSize((640, 480))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FileView.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.fileView_ctrl, 1, wx.ALL|wx.EXPAND, 2)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade
    def setText(self, filename):
        filename=filename.encode('ascii')  
        try:
            text=open(filename,"r").read()
            self.fileView_ctrl.SetValue(text)
        except:
            pass
# end of class FileView


class fileViewDialog(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        self.dialog_1 = FileView(None, -1, "")
        self.SetTopWindow(self.dialog_1)
        self.dialog_1.Show()
        return 1
    def setFileToOpen(self, filename):
        self.filename=filename
        self.dialog_1.setText(self.filename)
# end of class fileViewDialog

if __name__ == "__main__":
    fileView = fileViewDialog(0)
    fileView.MainLoop()
